print(getwd())
setwd("C:/Users/nikitha/OneDrive/Documents/RPROGRAM")
print(getwd())
data<-read.csv("input1.csv")
print(data)
print(is.data.frame(data))
print(nrow(data))
print(ncol(data))
sal<-max(data$salary)
print(sal)
result<-subset(data,salary==max(salary))
print(result)
result1<-subset(data,dept=="it")
print(result1)
result2<-subset(data,salary>600 & dept=="it")
print(result2)
result3<-subset(data,as.Date(start_date)>as.Date("2014-01-01"))
print(result3)